#Freeze-thaw cycling using FTCQuant
#Code generated by Angela Possinger and Erin Rooney, July 2020

#Packages----------------------------------
library(dplyr)
library(purrr)
library(tidyr)
library(ggplot2)
library(ggmap)
library(usmap)
library(reshape)
library(reshape2)
library(RColorBrewer)
library(ggalt)
library(plyr)
library(Rmisc)
library(ggstance)
library(GGally)
library(ggforce)
library(viridis)
library(ggrepel)
library(ggfortify)
library(gginnards)
library(ggspatial)
library(ggsn)
install_github("BajczA475/FTCQuant/FTCQuant")
library(FTCQuant)

#Set working directory or use Session > Set Working Directory > Choose directory-----------------------------
setwd("~/R/R/R Datasets/introductoryR-master")

#Load soil temp data as NEON data products------------------------------------
#5 cores/site (001, 002, 003, etc.), 7-9 depths per site (501, 502, 503, etc.)

load("Processed/activelayer_dat.RData")
#load("Processed/activelayer.RData")
#load("Processed/activelayer2.RData")
#load("Processed/fall1.RData")
#load("Processed/fall2.RData")
#load("Processed/summer1.RData")
#load("Processed/summer2.RData")
#load("Processed/spring1.RData")
#load("Processed/spring2.RData")
#load("Processed/winter1.RData")
#load("Processed/winter2.RData")
load("Processed/final_dat.RData")


#Data manipulation##########################
#freeze.thaw.analysis function requires a list of dataframes with col 1 = date and col 2 = temp data. 
#Each dataframe is only 1 unit (i.e., 1 site, 1 core, 1 depth, 1 date range) 

#Example: active layer Y1
#This makes a new dataframe of data element of the downloaded data
#activelayer1dat <- activelayer$ST_30_minute
alldat <- final_dat$ST_30_minute

#Reduce number of columns (otherwise next line will take forever/might crash the computer...)
#activelayer1dat <- activelayer1dat[,c("siteID","verticalPosition","horizontalPosition","startDateTime","soilTempMean")]
alldat <- alldat[,c("siteID","verticalPosition","horizontalPosition","startDateTime","soilTempMean")]


#Reformat from "long" to "wide" form. Now the first column is the date-time
#the other columns all correspond to one individual unit (probe), i.e. 1 site, 1 core, 1 depth 
#activelayer1dat_Wide <- dcast(activelayer1dat, startDateTime ~ siteID + verticalPosition + horizontalPosition)
alldat_wide <- dcast(alldat, startDateTime ~ siteID + verticalPosition + horizontalPosition)


#There is a problem with the freeze.thaw.analysis function with too many missing values. 
#For now, replacing columns with NA > 3% of timepoints with 0s (should be a flat line) 

#How many NAs is 3%?
#Max_NA <- nrow(activelayer1dat_Wide)*0.03

Max_NA <- nrow(alldat_wide)*0.03

#Count # of NAs in each column
NA_count <- as.data.frame(sapply(activelayer1dat_Wide, function(x) sum(is.na(x))))
colnames(NA_count) <- c("NA_count")

#Converts all columns with names that match rows in NA_count with NA > 3% to 0s 
activelayer1dat_Wide[,c(rownames(NA_count)[NA_count$NA_count >= Max_NA])] <- 0

#Convert date to character
activelayer1dat_Wide$startDateTime=as.character.Date(activelayer1dat_Wide$startDateTime)
names(activelayer1dat_Wide)[names(activelayer1dat_Wide) == 'startDateTime'] <- 'date'

#Dimensions of final dataframe
dim(activelayer1dat_Wide)

#Plotting ###################################
#Data for plotting individual site x location x depth time series 
activelayer1_plotting = activelayer1dat_Wide
activelayer1_plotting$date=as.POSIXct(activelayer1_plotting$date)

#Example plot replaced with 0s (flat line)
h = ggplot(activelayer1_plotting)
h + geom_line(aes(x=date, y=BARR_501_001))

#Example plot with all data
h = ggplot(activelayer1_plotting)
h + geom_line(aes(x=date, y=BONA_502_001))

#Example plot with all data
h = ggplot(activelayer1_plotting)
h + geom_line(aes(x=date, y=HEAL_502_002))


#Freeze-thaw analysis ####################################
#Names of all columns but date, which will become the names of each element in the data.list for freeze thaw function
#Number of columns to use in the data.list 
column_names=as.vector(colnames(activelayer1dat_Wide[,2:ncol(activelayer1dat_Wide)]))
column_number=as.vector(2:ncol(activelayer1dat_Wide))

#This function makes a list of elements, extracting row 1 (date) and then sequentially each column (y)
#Each date and data column is a new element in the list, named by the list of column names above (x) 
fun1 <- function(x,y) {
  data.list <- list(x = activelayer1dat_Wide[,c(1,y)])
}

#This applies the function to loop through the list of column names (x) and numbers (y) 
data.list.activelayer.Y1 = mapply(fun1,column_names,column_number)

#The actual analysis function: this is where the parameters can be changed
activelayer.FTC.Y1=freeze.thaw.analysis(data.list.activelayer.Y1, mag.vec=1, dur.vec=24, thres.vec=0)

#This takes the data column from the object and combines it with the names 
activelayer.FTC.Y1.dat = cbind(activelayer.FTC.Y1$data, column_names)

#Measurements to exclude?
Exclude = as.data.frame(rownames(NA_count)[NA_count$NA_count >= Max_NA])
Exclude$Label = rep("Exclude", length(Exclude))
colnames(Exclude)=c("column_names","Label")

activelayer.FTC.Y1.full <- Exclude %>% right_join(activelayer.FTC.Y1.dat, by=c("column_names"))
activelayer.FTC.Y1.full$Label[is.na(activelayer.FTC.Y1.full$Label)] = "Keep"

activelayer.FTC.Y1.full$Def1[activelayer.FTC.Y1.full$Label == "Exclude"] <- NA
activelayer.FTC.Y1.full$season=rep("activelayer",nrow(activelayer.FTC.Y1.full))
activelayer.FTC.Y1.full$year=rep("Y1",nrow(activelayer.FTC.Y1.full))

#Split column to create factors (depth and core)
activelayer.FTC.Y1.full$column_names_2=activelayer.FTC.Y1.full$column_names

#This is the final data for each original RData file. 
activelayer.FTC.Y1.full.final = activelayer.FTC.Y1.full %>% separate(column_names_2, c("site","depth","core"), sep="_")

                     
